#ifndef TIE_FLIGHT_TRACE_FORMAT_H
#define TIE_FLIGHT_TRACE_FORMAT_H

#include <stdint.h>

/* All integers in a flight trace are little-endian. Record sizes make the
 * stream forward-compatible: readers can skip event types they do not know. */
#define TIE_FLIGHT_TRACE_MAGIC "OTFTRC\0\1"
#define TIE_FLIGHT_TRACE_VERSION 3u
#define TIE_FLIGHT_TRACE_HEADER_SIZE 160u
#define TIE_FLIGHT_TRACE_RECORD_HEADER_SIZE 16u
#define TIE_FLIGHT_TRACE_FG_NAME_SIZE 12u
#define TIE_FLIGHT_TRACE_OBJECT_SIZE 48u
#define TIE_FLIGHT_TRACE_IDENTITY_SIZE 12u

#define TIE_TRACE_RECORD_FLAG_CRITICAL 0x0001u

enum TieFlightTraceHeaderFlags {
	TIE_TRACE_HEADER_FLAG_MISSION_ENDED = 0x00000001u,
	TIE_TRACE_HEADER_FLAG_APPLICATION_SHUTDOWN = 0x00000002u,
};

enum TieFlightTraceHeaderOffset {
	TIE_TRACE_HDR_MAGIC = 0,
	TIE_TRACE_HDR_VERSION = 8,
	TIE_TRACE_HDR_HEADER_SIZE = 10,
	TIE_TRACE_HDR_FLAGS = 12,
	TIE_TRACE_HDR_CAPACITY = 16,
	TIE_TRACE_HDR_BYTES_USED = 20,
	TIE_TRACE_HDR_RECORD_COUNT = 24,
	TIE_TRACE_HDR_DROPPED = 28,
	TIE_TRACE_HDR_PROFILE = 32,
	TIE_TRACE_HDR_DIFFICULTY = 36,
	TIE_TRACE_HDR_INITIAL_RNG = 40,
	TIE_TRACE_HDR_NUM_FG = 42,
	TIE_TRACE_HDR_START_TIME = 44,
	TIE_TRACE_HDR_MISSION = 52,
	TIE_TRACE_HDR_BUILD = 116,
	TIE_TRACE_HDR_MISSION_CHECKSUM = 148,
	TIE_TRACE_HDR_TIMING_MODE = 152,
	TIE_TRACE_HDR_DROPPED_CRITICAL = 156,
};

enum TieFlightTraceObjectOffset {
	TIE_TRACE_OBJECT_REF = 0,
	TIE_TRACE_OBJECT_ID = 2,
	TIE_TRACE_OBJECT_GENERATION = 4,
	TIE_TRACE_OBJECT_FG = 8,
	TIE_TRACE_OBJECT_SPECIES = 9,
	TIE_TRACE_OBJECT_GENUS = 10,
	TIE_TRACE_OBJECT_SIDE = 11,
	TIE_TRACE_OBJECT_CRAFT_INDEX = 12,
	TIE_TRACE_OBJECT_MODE = 13,
	TIE_TRACE_OBJECT_SUBMODE = 14,
	TIE_TRACE_OBJECT_FLIGHT_FLAG = 15,
	TIE_TRACE_OBJECT_DOCK_FLAGS = 16,
	TIE_TRACE_OBJECT_CATEGORY = 17,
	TIE_TRACE_OBJECT_COLLISION_RADIUS = 18,
	TIE_TRACE_OBJECT_TARGET = 20,
	TIE_TRACE_OBJECT_OWNER = 22,
	TIE_TRACE_OBJECT_X = 24,
	TIE_TRACE_OBJECT_Y = 28,
	TIE_TRACE_OBJECT_Z = 32,
	TIE_TRACE_OBJECT_VX = 36,
	TIE_TRACE_OBJECT_VY = 40,
	TIE_TRACE_OBJECT_VZ = 44,
};

enum TieFlightTraceIdentityOffset {
	TIE_TRACE_IDENTITY_REF = 0,
	TIE_TRACE_IDENTITY_ID = 2,
	TIE_TRACE_IDENTITY_GENERATION = 4,
	TIE_TRACE_IDENTITY_FG = 8,
	TIE_TRACE_IDENTITY_SPECIES = 9,
	TIE_TRACE_IDENTITY_CRAFT_INDEX = 10,
};

typedef enum TieFlightTraceRecordType {
	TIE_TRACE_RECORD_FG_DEF = 1,
	TIE_TRACE_RECORD_FRAME = 2,
	TIE_TRACE_RECORD_OBJECT_SPAWN = 3,
	TIE_TRACE_RECORD_OBJECT_REMOVED = 4,
	TIE_TRACE_RECORD_AI_CHANGE = 5,
	TIE_TRACE_RECORD_BOARD = 6,
	TIE_TRACE_RECORD_WEAPON = 7,
	TIE_TRACE_RECORD_COLLISION = 8,
	TIE_TRACE_RECORD_DAMAGE = 9,
	TIE_TRACE_RECORD_DEATH = 10,
	TIE_TRACE_RECORD_EXPLOSION = 11,
	TIE_TRACE_RECORD_FG_STATE = 12,
	TIE_TRACE_RECORD_MISSION_STATE = 13,
	TIE_TRACE_RECORD_TARGET_CHANGE = 14,
	TIE_TRACE_RECORD_OVERFLOW = 15,
	TIE_TRACE_RECORD_FG_EXIT = 16,
} TieFlightTraceRecordType;

typedef enum TieFlightTracePhase {
	TIE_TRACE_PHASE_SETUP = 0,
	TIE_TRACE_PHASE_TIME = 1,
	TIE_TRACE_PHASE_FG_STATUS = 2,
	TIE_TRACE_PHASE_AI = 3,
	TIE_TRACE_PHASE_WEAPONS = 4,
	TIE_TRACE_PHASE_DYNAMICS = 5,
	TIE_TRACE_PHASE_RENDER = 6,
	TIE_TRACE_PHASE_COLLISION = 7,
	TIE_TRACE_PHASE_MOVE = 8,
	TIE_TRACE_PHASE_ANIMATION = 9,
	TIE_TRACE_PHASE_OBJECTIVES = 10,
	TIE_TRACE_PHASE_END_FRAME = 11,
} TieFlightTracePhase;

typedef enum TieFlightTraceExitKind {
	TIE_TRACE_EXIT_UNKNOWN = 0,
	TIE_TRACE_EXIT_DESTROYED = 2,
	TIE_TRACE_EXIT_HYPERSPACE = 3,
	TIE_TRACE_EXIT_ENTERED_HANGAR = 4,
	TIE_TRACE_EXIT_PASSENGER = 7,
	TIE_TRACE_EXIT_SCRIPTED = 8,
} TieFlightTraceExitKind;

typedef enum TieFlightTraceRemovalKind {
	TIE_TRACE_REMOVAL_CLEARED = 1,
	TIE_TRACE_REMOVAL_REPLACED = 2,
} TieFlightTraceRemovalKind;

typedef enum TieFlightTraceBoardKind {
	TIE_TRACE_BOARD_APPROACH = 1,
	TIE_TRACE_BOARD_ALIGNING = 2,
	TIE_TRACE_BOARD_DOCKED = 3,
	TIE_TRACE_BOARD_TRANSFER = 4,
	TIE_TRACE_BOARD_CAPTURED = 5,
	TIE_TRACE_BOARD_DEPARTING = 6,
	TIE_TRACE_BOARD_COMPLETE = 7,
} TieFlightTraceBoardKind;

typedef enum TieFlightTraceCollisionKind {
	TIE_TRACE_COLLISION_CRAFT = 1,
	TIE_TRACE_COLLISION_PROJECTILE = 2,
	TIE_TRACE_COLLISION_STATIC = 3,
} TieFlightTraceCollisionKind;

typedef enum TieFlightTraceDeathKind {
	TIE_TRACE_DEATH_DAMAGE = 1,
	TIE_TRACE_DEATH_SYSTEMS_DISABLED = 2,
	TIE_TRACE_DEATH_EJECTED = 3,
} TieFlightTraceDeathKind;

typedef enum TieFlightTraceCause {
	TIE_TRACE_CAUSE_UNKNOWN = 0,
	TIE_TRACE_CAUSE_CRAFT_COLLISION = 1,
	TIE_TRACE_CAUSE_PROJECTILE = 2,
	TIE_TRACE_CAUSE_STATIC_COLLISION = 3,
	TIE_TRACE_CAUSE_EJECTED = 4,
	TIE_TRACE_CAUSE_SCRIPTED = 5,
} TieFlightTraceCause;

#endif
