/* Auto-generated from STRINGS.DAT messagetable[214].
 * Each value is the template_id passed to msg_messageprintf and indexes
 * messagetable[]. See docs/strings-dat-messagetable.md for the full text. */

#ifndef TIE_MSG_TEMPLATES_H
#define TIE_MSG_TEMPLATES_H

typedef enum MsgTemplate {
	MSG_TIE_VERSION = 0,                /* <C6>TIE Fighter [Final V2.0] 11/28/94 */
	MSG_PAUSED = 1,                     /* <C6>Mission paused.  Press any key to continue */
	MSG_RESUMED = 2,                    /* <C6>Mission resumed */
	MSG_LASERS_ARMED = 3,               /* <C3>Laser cannons armed */
	MSG_IONS_ARMED = 4,                 /* <C3>Ion cannons armed */
	MSG_LAUNCHERS_ARMED = 5,            /* <C3>* launchers armed */
	MSG_LAUNCHERS_SINGLE = 6,           /* <C3>* launchers set to [single fire */
	MSG_LAUNCHERS_DUAL = 7,             /* <C3>* launchers set to [dual fire */
	MSG_PROTON_TORPEDO = 8,             /* Proton torpedo */
	MSG_CONCUSSION_MISSILE = 9,         /* Concussion missile */
	MSG_CANNON_SINGLE = 10,             /* <C3>Cannons set to [single fire */
	MSG_CANNON_DUAL = 11,               /* <C3>Cannons set to [dual fire */
	MSG_CANNON_LINKED = 12,             /* <C3>Cannons [fire linked */
	MSG_SHIELDS_SET = 13,               /* <C3>Deflector shields set * */
	MSG_SHIELD_FORWARD = 14,            /* [full strength forward */
	MSG_SHIELD_BALANCED = 15,           /* [even strength forward and aft */
	MSG_SHIELD_AFT = 16,                /* [full strength aft */
	MSG_CANNON_RATE = 17,               /* <C3>Cannon* rate */
	MSG_SHIELD_RATE = 18,               /* <C3>Shield* rate */
	MSG_ENGINE_MAX = 19,                /*  power redirected to engines at [maximum] */
	MSG_ENGINE_MIN = 20,                /*  power redirected to engines at [minimum] */
	MSG_RECHARGE_NORMAL = 21,           /* s recharging at [normal] */
	MSG_RECHARGE_INCREASED = 22,        /* s recharging at [increased] */
	MSG_RECHARGE_MAXIMUM = 23,          /* s recharging at [maximum] */
	MSG_SYSTEM_STATUS = 24,             /* <C3>[*] system is * */
	MSG_SYS_DAMAGED = 25,               /* damaged and inoperative */
	MSG_SYS_REPAIRED = 26,              /* repaired */
	MSG_SYS_ENGINE = 27,                /* Engine */
	MSG_SYS_FLIGHT_CONTROL = 28,        /* Flight control */
	MSG_SYS_LASER = 29,                 /* Laser */
	MSG_SYS_ION_CANNON = 30,            /* Ion Cannon */
	MSG_SYS_LAUNCHER = 31,              /* Warhead Launcher */
	MSG_SYS_BEAM_WEAPON = 32,           /* Beam Weapon */
	MSG_SYS_TARGETING = 33,             /* Targeting computer */
	MSG_SYS_AUTO_EJECT = 34,            /* Auto-ejection system */
	MSG_SYS_SHIELD = 35,                /* Deflector shield */
	MSG_SYS_HYPERDRIVE = 36,            /* Hyperdrive */
	MSG_GFX_DETAIL = 37,                /* <C6>Graphics detail set to [*] level */
	MSG_GFX_LOWEST = 38,                /* lowest */
	MSG_GFX_LOW = 39,                   /* low */
	MSG_GFX_HIGH = 40,                  /* high */
	MSG_GFX_HIGHEST = 41,               /* highest */
	MSG_HYPER_PREP = 42,                /* <C3>Preparing for jump to light speed.. */
	MSG_HYPER_ABORTED = 43,             /* <C3>Hyperspace jump aborted */
	MSG_HYPER_COMPLETED = 44,           /* <C3>Hyperspace jump completed */
	MSG_NEW_CRAFT_ALERT = 45,           /* <C2>New craft alert, [&[w1] *] at [&[w2]] km */
	MSG_NEW_CRAFT_ALERT_PLURAL = 46,    /* <C2>New craft alert, [&[w1] *s] at [&[w2]] km */
	MSG_BLANK_PADDING = 47,             /*                       */
	MSG_LEVEL_COMPLETED = 48,           /* <C3>Congratulations! Level Completed.  Time Left:       Bonus: */
	MSG_BONUS_AWARDED = 49,             /* <C3>Bonus points awarded: &[w4] */
	MSG_ENEMY_LOCK_PROMPT = 50,         /* <C4>An enemy craft is attempting missile lock, [should it be tar */
	MSG_MISSILE_WARNING_PROMPT = 51,    /* <C4>Missile Warning! [Key to Target? */
	MSG_MISSILE_TARGETED_OK = 52,       /* <C4>Missile was targeted */
	MSG_HYPER_OBJECT_BLOCK = 53,        /* <C3>Object detected in jump path, hyperspace jump aborted */
	MSG_REPLAY_CAMERA_ON = 54,          /* <C6>Replay camera [on */
	MSG_REPLAY_CAMERA_OFF = 55,         /* <C6>Replay camera [off */
	MSG_CAMERA_FAIL = 56,               /* <C6>Error! Failed to start camera */
	MSG_CAMERA_SAVING = 57,             /* <C6>Camera footage is being saved to disk */
	MSG_CAMERA_SAVED = 58,              /* <C6>Camera footage saved */
	MSG_CAMERA_FILM_USED = 59,          /* <C6>Camera film used up */
	MSG_CAMERA_LOADING = 60,            /* <C6>Loading camera footage from disk */
	MSG_FILM_NONE = 61,                 /* <C6>No film recorded */
	MSG_FILM_END = 62,                  /* <C6>At end of film */
	MSG_FILM_STARTED = 63,              /* <C6>Film started */
	MSG_FILM_STOPPED = 64,              /* <C6>Film stopped */
	MSG_FILM_ADVANCE_ON = 65,           /* <C6>Film advance on */
	MSG_FILM_ADVANCE_OFF = 66,          /* <C6>Film advance off */
	MSG_FILM_REWOUND = 67,              /* <C6>Film rewound to start */
	MSG_CAMERA_FOLLOW = 68,             /* <C6>Camera now in [FOLLOW] mode */
	MSG_CAMERA_FREE = 69,               /* <C6>Camera now in [FREE] mode */
	MSG_MISSION_ENDS_2MIN = 70,         /* <C1>Mission ends in [2] minutes */
	MSG_MISSION_ENDS_1MIN = 71,         /* <C1>Mission ends in [1] minute */
	MSG_MISSION_TIME_EXPIRED = 72,      /* <C1>Mission time expired, hyperspace sequence begun.. */
	MSG_TRACTOR_PROMPT = 73,            /* <C4>Hit [Space Bar] to activate tractor beam and enter hangar */
	MSG_OBJECTIVES_FAILED = 74,         /* <C1>Mission objectives can not be finished, abort mission! */
	MSG_ENTER_FILENAME = 75,            /* <\x0e>Enter file name: */
	MSG_FILE_REPLACE = 76,              /* <\x0c>File Exists! Replace it? */
	MSG_REPLAY_SAVED = 77,              /* <\x0e>Replay clip saved */
	MSG_REPLAY_NOT_SAVED = 78,          /* <\x0c>Replay clip not saved */
	MSG_FILE_ERROR = 79,                /* <\x0c>File Error! */
	MSG_THROTTLE_SET = 80,              /* <C3>Engine throttle set to [* */
	MSG_THROTTLE_ZERO = 81,             /* no power */
	MSG_THROTTLE_1_3 = 82,              /* 1/3 power */
	MSG_THROTTLE_2_3 = 83,              /* 2/3 power */
	MSG_THROTTLE_FULL = 84,             /* full power */
	MSG_CMD_TRACK_TOGGLE = 85,          /* <C3>Component tracking in CMD display turned [*] */
	MSG_OFF = 86,                       /* OFF */
	MSG_ON = 87,                        /* ON */
	MSG_SFOIL_OPENING = 88,             /* <C3>S-Foils opening */
	MSG_SFOIL_CLOSING = 89,             /* <C3>S-Foils closing */
	MSG_SFOIL_AT_POS = 90,              /* <C3>S-Foils have reached [*] position */
	MSG_SFOIL_OPEN = 91,                /* open */
	MSG_SFOIL_CLOSED = 92,              /* closed */
	MSG_XFER_SHIELDS_TO_CANNON = 93,    /* <C3>Transfering partial power from shields to [cannon system */
	MSG_XFER_CANNON_TO_SHIELDS = 94,    /* <C3>Transfering partial power from cannons to [shields */
	MSG_CRAFT_REPORT_FG = 95,           /* <C2>[* * &[w1]] * */
	MSG_CRAFT_REPORT = 96,              /* <C2>[* *] * */
	MSG_HAS_HYPERED = 97,               /* has entered hyperspace */
	MSG_HAS_DESTROYED = 98,             /* has been [destroyed */
	MSG_HAS_DISABLED = 99,              /* has been [disabled */
	MSG_HAS_REPAIRED = 100,             /* has been [repaired */
	MSG_HAS_CAPTURED = 101,             /* has been [captured */
	MSG_HAS_DOCKED = 102,               /* has [docked */
	MSG_HAS_TARGETED = 103,             /* has been targeted */
	MSG_REPORT_FROM_FG = 104,           /* <C3>[* &[w1]] from flight group [*] * */
	MSG_REPORT_FROM = 105,              /* <C3>[* *] * */
	MSG_LAUNCHER_EMPTY = 106,           /* <C3>* launcher empty */
	MSG_FIRED_SINGLE = 107,             /* <C3>* fired */
	MSG_FIRED_PLURAL = 108,             /* <C3>*s fired */
	MSG_HAS_ENTERED_HANGAR = 109,       /* has entered hangar */
	MSG_ACK_FG_INDEXED = 110,           /* <C1>Message acknowledged: [* * &[w1]] * */
	MSG_ACK_FG = 111,                   /* <C1>Message acknowledged: [* *] * */
	MSG_HEADING_HOME = 112,             /* heading home */
	MSG_COMING_TO_AID = 113,            /* coming to your aid */
	MSG_EVASIVE = 114,                  /* making evasive maneuver */
	MSG_WAITING_ORDERS = 115,           /* waiting for further orders */
	MSG_PROCEEDING = 116,               /* proceeding with mission */
	MSG_USING_TARGET = 117,             /* using designated target */
	MSG_IGNORING_TARGET = 118,          /* ignoring target */
	MSG_DOCKING_COMPLETE = 119,         /* reports docking operation complete */
	MSG_REPORTING_FG_INDEXED = 120,     /* <C1>[* * &[w1]] reporting in: * */
	MSG_REPORTING_FG = 121,             /* <C1>[* *] reporting in: * */
	MSG_HOLDING_STEADY = 122,           /* holding steady */
	MSG_ON_PATROL = 123,                /* on patrol */
	MSG_PROTECTING_CRAFT = 124,         /* protecting craft */
	MSG_PATROL_TO_ATTACK = 125,         /* patrolling for craft to attack */
	MSG_PATROL_FOR_ESCORTERS = 126,     /* patrolling for escorters */
	MSG_ATTACK_RUN_SETUP = 127,         /* setting up for attack run */
	MSG_ATTACKING_TARGET = 128,         /* attacking target */
	MSG_DOING_EVASIVE = 129,            /* doing evasive maneuver */
	MSG_FOLLOWING_LEADER = 130,         /* following flight leader */
	MSG_LOOK_TO_DISABLE = 131,          /* looking for craft to disable */
	MSG_FLYING_ESCORT = 132,            /* flying escort */
	MSG_LOOK_TO_BOARD = 133,            /* looking for craft to board */
	MSG_LOOK_TO_CAPTURE = 134,          /* looking for craft to capture */
	MSG_LOOK_TO_PICKUP = 135,           /* looking for craft to pick up */
	MSG_PERFORMING_DOCKING = 136,       /* performing docking operation */
	MSG_FLYING_RENDEZVOUS = 137,        /* flying to rendezvous point */
	MSG_AWAIT_BOARDING_CRAFT = 138,     /* awaiting boarding craft */
	MSG_AWAIT_BOARDING = 139,           /* awaiting boarding */
	MSG_HOLDING_STATION = 140,          /* holding station */
	MSG_FLYING_HOME = 141,              /* flying home */
	MSG_ENTERING_HANGAR = 142,          /* entering hangar */
	MSG_EXITING_HANGAR = 143,           /* exiting hangar */
	MSG_ENTERING_HYPER = 144,           /* entering hyperspace */
	MSG_EXITING_HYPER = 145,            /* exiting hyperspace */
	MSG_FOLLOWING_PLAN = 146,           /* following flight plan */
	MSG_AWAIT_RETURN = 147,             /* awaiting return of craft */
	MSG_AWAIT_LAUNCH = 148,             /* awaiting launch of craft */
	MSG_CHANGING_ORDERS = 149,          /* changing orders */
	MSG_AWAIT_FURTHER = 150,            /* awaiting further orders */
	MSG_WAITING = 151,                  /* waiting */
	MSG_DROPPING_OFF = 152,             /* dropping off craft */
	MSG_RESERVED_153 = 153,             /* (unused/empty) */
	MSG_RESERVED_154 = 154,             /* (unused/empty) */
	MSG_RESERVED_155 = 155,             /* (unused/empty) */
	MSG_RESERVED_156 = 156,             /* (unused/empty) */
	MSG_RESERVED_157 = 157,             /* (unused/empty) */
	MSG_RESERVED_158 = 158,             /* (unused/empty) */
	MSG_RESERVED_159 = 159,             /* (unused/empty) */
	MSG_PRIMARY_COMPLETE = 160,         /* <C1>Excellent job!  Primary mission objectives completed */
	MSG_GENERIC_STAR = 161,             /* <C1>* */
	MSG_EJECTED = 162,                  /* <C3>You have ejected safely */
	MSG_BONUS_PRIOR_LEVELS = 163,       /* &[w1]0000 points awarded for previous levels */
	MSG_NO_SIM_AVAILABLE = 164,         /* <\x0c>Cannot enter simulation at this point! */
	MSG_LAUNCHER = 165,                 /* Launcher */
	MSG_CANNON = 166,                   /* Cannon */
	MSG_DIED = 167,                     /* <C3>You have died */
	MSG_RESERVED_168 = 168,             /* (unused/empty) */
	MSG_ENTERING_HYPER_NOW = 169,       /* <C3>Entering hyperspace */
	MSG_TARGET_LOST = 170,              /* <C3>Threat display target no longer available */
	MSG_HAS_INSPECTED = 171,            /* has been [inspected */
	MSG_NO_SUCH_SYSTEM = 172,           /* <C1>This craft is not equipped with a [*] system */
	MSG_NO_TARGET = 173,                /* <C3>No craft targeted */
	MSG_GENERIC_STAR_INFO = 174,        /* <C1>* */
	MSG_CRAFT_NOT_RESPONDING = 175,     /* <C1>Craft not responding to order */
	MSG_SECONDARY_COMPLETE = 176,       /* <C1>Superb work! Secondary mission objectives completed */
	MSG_BONUS_COMPLETE = 177,           /* <C1>Superlative job! Bonus mission objectives completed */
	MSG_NO_REINFORCEMENTS = 178,        /* <C1>No reinforcements available */
	MSG_REINFORCE_ACK = 179,            /* <C7>Request for reinforcements acknowledged */
	MSG_REINFORCE_ALREADY_USED = 180,   /* <C1>Reinforcements already sent, no more available */
	MSG_DOCKED_WITH = 181,              /* <C2>[*] has docked with [*] */
	MSG_CRAFT_ENTERING_AT = 182,        /* <C1>[* *] entering area at [&[w2]] km */
	MSG_CRAFT_GROUP_ENTERING_AT = 183,  /* <C1>[&[w1] *s] from FG [*] entering area at [&[w2]] km */
	MSG_ADV_PROTON_TORPEDO = 184,       /* Advanced proton torpedo */
	MSG_ADV_CONCUSSION_MISSILE = 185,   /* Advanced concussion missile */
	MSG_HEAVY_BOMB = 186,               /* Heavy space bomb */
	MSG_HEAVY_ROCKET = 187,             /* Heavy rocket */
	MSG_MAGNETIC_PULSE = 188,           /* Magnetic pulse */
	MSG_NO_HYPERDRIVE_RETURN = 189,     /* <C3>No hyperdrive unit, return to [*] */
	MSG_NO_HYPERDRIVE_RETURN_ALT = 190, /* <C3>No hyperdrive unit, return to [*] or to [*] */
	MSG_BEAM_ON = 191,                  /* <C3>* beam] system activated */
	MSG_BEAM_OFF = 192,                 /* <C3>* beam] system de-activated */
	MSG_BEAM_TRACTOR = 193,             /* Tractor */
	MSG_BEAM_JAMMING = 194,             /* Jamming */
	MSG_BEAM_DECOY = 195,               /* Decoy */
	MSG_BEAM_RATE = 196,                /* <C3>Beam* rate */
	MSG_REINFORCE_PROMPT = 197,         /* <C4>Hit [Space Bar] to confirm reinforcement request */
	MSG_RESUPPLIES_INCOMING = 198,      /* resupplies are on the way */
	MSG_TIME_ACCEL = 199,               /* <C6>Time accelerated to [&[w2]]X normal time */
	MSG_TIME_NORMAL = 200,              /* <C6>Normal time set */
	MSG_WARHEAD_TARGETED = 201,         /* <C7>Warhead targeted */
	MSG_END_MISSION_PROMPT = 202,       /* <C4>Press [Space Bar] to end mission */
	MSG_COLLISION_OCCURRED = 203,       /* <C3>Collision with another craft has occured! */
	MSG_INTERDICTOR_BLOCK = 204,        /* <C3>Enemy Interdictor prevents hyperdrive unit from functioning! */
	MSG_ACK_FG_PLAIN = 205,             /* <C1>Message acknowledged: [Flight Group *] * */
	MSG_MATCHING_SPEED = 206,           /* <C3>Matching speed with target */
	MSG_MATCHING_SPEED_MAX = 207,       /* <C3>Trying to match speeds with target, throttle set to maximum */
	MSG_FRIENDLY_KILL = 208,            /* <C2>You have destroyed a craft on your own side */
	MSG_MISSILE_DESTROYED = 209,        /* <C4>Missile destroyed */
	MSG_WARHEAD_DRAINED_CANNON = 210,   /* <C3>Warhead impact drained all cannon energy! */
	MSG_OVERDRIVE_ENGAGED = 211,        /* <C3>Engine overdrive boosters [engaged] */
	MSG_OVERDRIVE_DISENGAGED = 212,     /* <C3>Engine overdrive boosters [disengaged] */
	MSG_OVERDRIVE_FAIL = 213,           /* <C3>Engine overdrive boosters can not be engaged */
	MSG_BRIGHTNESS_SET = 214,           /* retail only: <C6>Screen brightness level * */
} MsgTemplate;

#endif /* TIE_MSG_TEMPLATES_H */
