/* Generates a YAML rectangle mesh covering a PNG's nontransparent cells.
 * Covered grid cells are greedily merged rightward and downward. */

#include <stdint.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>

#define STB_IMAGE_IMPLEMENTATION
#define STBI_ONLY_PNG
#include "stb_image.h"

static int TieCoverageMesh_ParseInt(const char* s, int fallback) {
	char* end = NULL;
	long v = strtol(s, &end, 10);
	return (end && *end == '\0') ? (int)v : fallback;
}

int main(int argc, char** argv) {
	const char *in_path = NULL, *out_path = NULL;
	int cell = 16;
	int alpha_thresh = 0;

	for (int i = 1; i < argc; i++) {
		if (!strcmp(argv[i], "--cell") && i + 1 < argc)
			cell = TieCoverageMesh_ParseInt(argv[++i], cell);
		else if (!strcmp(argv[i], "--alpha") && i + 1 < argc)
			alpha_thresh = TieCoverageMesh_ParseInt(argv[++i], alpha_thresh);
		else if (!in_path)
			in_path = argv[i];
		else if (!out_path)
			out_path = argv[i];
	}
	if (!in_path || !out_path || cell < 1) {
		fprintf(stderr, "usage: %s in.png out.yaml [--cell N] [--alpha T]\n", argv[0]);
		return 2;
	}

	int w = 0, h = 0, comp = 0;
	uint8_t* px = stbi_load(in_path, &w, &h, &comp, 4); /* force RGBA */
	if (!px) {
		fprintf(stderr, "coverage_mesh: cannot load %s: %s\n", in_path, stbi_failure_reason());
		return 1;
	}

	const int gw = (w + cell - 1) / cell;
	const int gh = (h + cell - 1) / cell;
	uint8_t* covered = (uint8_t*)calloc((size_t)gw * gh, 1);
	uint8_t* consumed = (uint8_t*)calloc((size_t)gw * gh, 1);
	if (!covered || !consumed) {
		fprintf(stderr, "oom\n");
		return 1;
	}

	/* Mark covered cells: any texel in the cell with alpha > threshold. */
	for (int y = 0; y < h; y++) {
		const uint8_t* row = px + (size_t)y * w * 4;
		const int cy = y / cell;
		for (int x = 0; x < w; x++) {
			if (row[x * 4 + 3] > alpha_thresh)
				covered[(size_t)cy * gw + (x / cell)] = 1;
		}
	}

	FILE* f = fopen(out_path, "wb");
	if (!f) {
		fprintf(stderr, "cannot write %s\n", out_path);
		return 1;
	}
	fprintf(f, "# coverage mesh for %s — opaque-region rectangles (px).\n", in_path);
	fprintf(f, "# Generated by coverage_mesh; do not hand-edit.\n");
	fprintf(f, "image: { w: %d, h: %d }\n", w, h);
	fprintf(f, "cell: %d\n", cell);
	fprintf(f, "alpha_threshold: %d\n", alpha_thresh);
	fprintf(f, "rects:\n");

	long covered_cells = 0, rect_count = 0;
	for (int i = 0; i < gw * gh; i++)
		covered_cells += covered[i];

	/* Greedy rectangle merge over the covered grid: grow right along the
	 * row, then down while the full width stays covered. The count is
	 * bounded by the cell-resolution boundary (a diagonal/curved edge needs
	 * ~1 rect per boundary step — irreducible for axis-aligned rects), so a
	 * fancier partition doesn't help; this simple pass is at/near the
	 * axis-aligned minimum. Rects tile exactly the covered cells. */
	for (int cy = 0; cy < gh; cy++) {
		for (int cx = 0; cx < gw; cx++) {
			const size_t base = (size_t)cy * gw + cx;
			if (!covered[base] || consumed[base])
				continue;

			int x2 = cx;
			while (x2 + 1 < gw && covered[(size_t)cy * gw + (x2 + 1)] &&
				   !consumed[(size_t)cy * gw + (x2 + 1)])
				x2++;

			int y2 = cy;
			for (;;) {
				if (y2 + 1 >= gh)
					break;
				int ok = 1;
				for (int x = cx; x <= x2; x++) {
					const size_t c = (size_t)(y2 + 1) * gw + x;
					if (!covered[c] || consumed[c]) {
						ok = 0;
						break;
					}
				}
				if (!ok)
					break;
				y2++;
			}

			for (int y = cy; y <= y2; y++)
				for (int x = cx; x <= x2; x++)
					consumed[(size_t)y * gw + x] = 1;

			/* Cell box → pixel box, clamped to the image (last cell may
			 * overhang). */
			int rx = cx * cell, ry = cy * cell;
			int rw = (x2 + 1) * cell;
			if (rw > w)
				rw = w;
			rw -= rx;
			int rh = (y2 + 1) * cell;
			if (rh > h)
				rh = h;
			rh -= ry;
			fprintf(f, "  - { x: %d, y: %d, w: %d, h: %d }\n", rx, ry, rw, rh);
			rect_count++;
		}
	}

	fclose(f);
	stbi_image_free(px);
	free(covered);
	free(consumed);

	const long total_cells = (long)gw * gh;
	fprintf(stderr,
			"coverage_mesh: %dx%d, cell=%d → grid %dx%d (%ld cells), "
			"%ld covered (%.1f%%), %ld rects\n",
			w, h, cell, gw, gh, total_cells, covered_cells,
			total_cells ? 100.0 * (double)covered_cells / (double)total_cells : 0.0, rect_count);
	return 0;
}
